[[entry]]
played_at = "2026-06-22T01:20:10Z"
path = "https://www.youtube.com/watch?v=vNqG14m4A-I"
title = "Mix Beéle (Loco, Frente Al Mar, Mi Refe, La Plena, Vagabundo y Más)"
artist = "DJ RDIX"
duration_secs = 1349

[[entry]]
played_at = "2026-06-21T22:46:05Z"
path = "https://www.youtube.com/watch?v=wMR80j9QHRY"
title = "Eladio Carrión, TopBoy TGR - Daikoku (Video Oficial) | CORSA"
artist = "Eladio Carrion and Topboy TGR"
duration_secs = 245

[[entry]]
played_at = "2026-06-21T22:42:00Z"
path = "https://www.youtube.com/watch?v=Xty2gi5cMa8"
title = "Drake - First Person Shooter ft. J. Cole"
artist = "Drake"
duration_secs = 301

[[entry]]
played_at = "2026-06-21T21:07:40Z"
path = "https://www.youtube.com/watch?v=wMR80j9QHRY"
title = "Eladio Carrión, TopBoy TGR - Daikoku (Video Oficial) | CORSA"
artist = "Eladio Carrion and Topboy TGR"
duration_secs = 245

[[entry]]
played_at = "2026-06-19T04:55:01Z"
path = "/home/johanrodallega/Música/Music Of Android/LLEVAME AL LUGAR SANTISIMO   JUAN CARLOS ALVARADO ( 160kbps ).mp3"
title = "LLEVAME AL LUGAR SANTISIMO   JUAN CARLOS ALVARADO"
artist = "FABIÁN VALENCIA"

[[entry]]
played_at = "2026-06-14T19:03:42Z"
path = "https://www.youtube.com/watch?v=NomGdaA-g0w"
title = "What You Heard"
artist = "Sonder"
duration_secs = 239
