# This config is a STUB! This should never be generated.
# Use the default lua config from https://github.com/hyprwm/Hyprland/blob/main/example/hyprland.lua

source = ~/.cache/wal/colors-hyprland.conf

$mainMod = SUPER
$terminal = kitty
$fileManager = thunar
$menu = rofi -show drun
$browser = Brave

### INI ###
source = ~/.config/hypr/pywal-colors.conf

decoration {
    rounding = 14

    blur {
        enabled = true
        size = 8
        passes = 2
    }
    
    shadow {
        enabled = true
        range = 50
        render_power = 3
        color = rgba(00000055)
    }
}

general {
    border_size = 3

    col.active_border = $color4
    col.inactive_border = $color0

    gaps_in = 5
    gaps_out = 10
}
  

### ANIMATIONS ###

animations {
    enabled = yes

    bezier = smooth,0.25,0.1,0.25,1.0

    animation = windows,1,5,smooth
    animation = windowsOut,1,5,smooth,popin 80%
    animation = border,1,8,smooth
    animation = fade,1,5,smooth
    animation = workspaces,1,6,smooth
}

### KEYBINDS ###
bind = SUPER SHIFT, H, movewindow, l
bind = SUPER SHIFT, L, movewindow, r
bind = SUPER SHIFT, K, movewindow, u
bind = SUPER SHIFT, J, movewindow, d

bind = SUPER, H, movefocus, l
bind = SUPER, L, movefocus, r 
bind = SUPER, K, movefocus, u
bind = SUPER, J, movefocus, d
bind = SUPER, W, exec, ~/.config/hypr/scripts/rofi-wallpaper.sh
bind = SUPER, B, exec, hyprlock
bind = SUPER, P, exec, ~/.config/hypr/scripts/screenshot.sh

# Volumen
bindel = , XF86AudioRaiseVolume, exec, wpctl set-volume -l 1.5 @DEFAULT_AUDIO_SINK@ 5%+
bindel = , XF86AudioLowerVolume, exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-
bindl = , XF86AudioMute, exec, wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle

# Brillo
bindel = , XF86MonBrightnessUp, exec, brightnessctl set +5%
bindel = , XF86MonBrightnessDown, exec, brightnessctl set 5%-


### EJECUTABLES###
#monitor = eDP-1,1920x1080,auto,1

#monitor=HDMI-A-1,1920x1080@180,0x0,1
monitor=eDP-1,1920x1080@60,1920x0,1 

# exec-once = hyprpaper
exec-once = waybar
exec-once = dunst
exec-once = blueman-applet
exec-once = nm-applet
exec-once = /usr/lib/polkit-kde-authentication-agent-1
exec-once = awww-daemon
exec-once = swaync
exec-once = sleep 1 && awww restore
exec-once = /usr/bin/kwalletd6
exec-once = /usr/lib/pam_kwallet_init

### KEYBOARD CONFIGURATION ###
	input {
	kb_layout = latam
	}

  ### WORKSPACES ###
bind = SUPER, 1, workspace, 1 
bind = SUPER, 2, workspace, 2
bind = SUPER, 3, workspace, 3
bind = SUPER, 4, workspace, 4
bind = SUPER, 5, workspace, 5
bind = SUPER, 6, workspace, 6
bind = SUPER, 7, workspace, 7

bind = SUPER SHIFT, 1, movetoworkspace, 1 
bind = SUPER SHIFT, 2, movetoworkspace, 2 
bind = SUPER SHIFT, 3, movetoworkspace, 3 
bind = SUPER SHIFT, 4, movetoworkspace, 4
bind = SUPER SHIFT, 5, movetoworkspace, 5 
bind = SUPER SHIFT, 6, movetoworkspace, 6 
bind = SUPER SHIFT, 7, movetoworkspace, 7 


bind = $mainMod, Return, exec, $terminal
bind = $mainMod, Q, killactive,
bind = $mainMod, M, exec, command -v hyprshutdown >/dev/null 2>&1 && hyprshutdown || hyprctl dispatch exit
bind = $mainMod, E, exec, $fileManager
bind = $mainMod, V, togglefloating,
bind = $mainMod, D, exec, $menu
#bind = $mainMod, F, exec, brave

bind = SUPER ALT, B, exec, kitty bluetuith
bind = SUPER ALT, N, exec, brave
bind = SUPER ALT, F, exec, firefox
bind = SUPER ALT, C, exec, kitty cliamp


### REGLAS

