-- Generated by nwg-displays on 2026-06-18 at 21:29:56. Do not edit manually.

hl.monitor({
    output = "eDP-1",
    mode = "1920x1080@59.98",
    position = "0x0",
    scale = 1.0
})
hl.monitor({
    output = "HDMI-A-1",
    mode = "1920x1080@179.96",
    position = "1920x0",
    scale = 1.0
})
