[gdrive]
type = drive
client_id = 718887186265-hrjc8v1tns6pqujglb742790rb17af2p.apps.googleusercontent.com
client_secret = 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
scope = drive
token = {"access_token":"ya29.a0AQvPyIOYOj8jcEMabXM2zTUJPrn7iUD0i81vATZsZlrolu59dXebpe7JLdhc_p6i2F8ozwmjNWLo6qVvlxVuLlOT-MSqjTimd3I_GoVvBKEg2hCT-P0dEAqW8RxPRCjnk92aeA-QMzK0UuyvYhyWA7wXtIQ1aqJxb4dlSkt2jyn4jCLNjbJO6l4bzVUTRarZtxYnP31iaCgYKAU4SARcSFQHGX2MiVq6hEcKmAi5tS33wewkuhA0207","token_type":"Bearer","refresh_token":"1//05niDw10cSF5JCgYIARAAGAUSNwF-L9IrS9kjLhYFei3Pc1emESATnfV-BsIi06NVoDjUAXupHbPI1VJfa-sjkkbo1t3OFGHvzO8","expiry":"2026-06-03T07:28:14.397044981-05:00","expires_in":3599}
team_drive = 

